services:
  app:
    image: discord-chatbot:latest
    volumes:
      - ../config.json:/app/config.json:ro
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
      - DB_IP=host.docker.internal
      - DB_PORT=5432
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"